### PR TITLE
Fixing an unterminated response body

### LINKED ISSUE #545: Plug.Conn.NotSentError error
**Message**

```
  ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
```

**Backtrace (last 10 lines)**

```
lib/phoenix/endpoint/cowboy2_handler.ex:110 Phoenix.Endpoint.Cowboy2Handler.maybe_send/2
lib/phoenix/endpoint/cowboy2_handler.ex:66 Phoenix.Endpoint.Cowboy2Handler.init/4
(cowboy 2.8.0) /tmp/glimesh.tv/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
(cowboy 2.8.0) /tmp/glimesh.tv/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
(cowboy 2.8.0) /tmp/glimesh.tv/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
proc_lib.erl:226 :proc_lib.init_p_do_apply/3
```

### PR DESCRIPTION
**Pull request by clone1018**
Potentially fixes #545

### CODE REVIEW

File: priv/repo/migrations/20210303192147_fix_discord_invite_links.exs [hunk 1]
```diff
@@ -7,7 +7,8 @@ defmodule Glimesh.Repo.Migrations.FixDiscordInviteLinks do
     users =
       Glimesh.Repo.all(
         from(u in "users",
-        select: %Glimesh.Accounts.User{id: u.id, social_discord: u.social_discord})
+          select: %Glimesh.Accounts.User{id: u.id, social_discord: u.social_discord}
+        )
```
Comment (clone1018) [inline priv/repo/migrations/20210303192147_fix_discord_invite_links.exs:11]: Just sneaking this in

**Comment by clone1018** [comment]
Need this out now so I can reconcile our payouts before tomorrow.
